//! Classifier tests against the tiny fixture model.
//!
//! tiny_model.onnx (generated by tests/fixtures/make_tiny_model.py) is a
//! ReduceMean-over-time + Softmax graph: the channel with the largest mean
//! wins. That lets each output class be forced deterministically.

use edge_ai_classifier::inference::classifier::Classifier;
use edge_ai_classifier::inference::model_loader::{
    load_verified_model, sha256_hex, ModelLoadError,
};
use edge_ai_classifier::inference::types::{AnomalyType, WINDOW_SECONDS, WINDOW_SIZE};
use std::path::PathBuf;

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/tiny_model.onnx")
}

fn fixture_hash() -> String {
    sha256_hex(&std::fs::read(fixture_path()).unwrap())
}

/// Window where one channel dominates -> that class index wins.
fn window_favoring(channel: usize) -> [f32; WINDOW_SIZE] {
    let mut window = [0.0f32; WINDOW_SIZE];
    for slot in &mut window[channel * WINDOW_SECONDS..(channel + 1) * WINDOW_SECONDS] {
        *slot = 10.0;
    }
    window
}

#[test]
fn model_loads_with_correct_hash() {
    let session = load_verified_model(&fixture_path(), &fixture_hash());
    assert!(session.is_ok());
}

#[test]
fn model_load_fails_on_wrong_hash() {
    let result = load_verified_model(&fixture_path(), "deadbeef");
    match result {
        Err(ModelLoadError::HashMismatch { expected, .. }) => {
            assert_eq!(expected, "deadbeef");
        }
        other => panic!("expected HashMismatch, got {other:?}"),
    }
}

#[test]
fn hash_comparison_is_case_insensitive() {
    let upper = fixture_hash().to_uppercase();
    assert!(load_verified_model(&fixture_path(), &upper).is_ok());
}

#[test]
fn classifies_each_class_from_dominant_channel() {
    let session = load_verified_model(&fixture_path(), &fixture_hash()).unwrap();
    let mut classifier = Classifier::new(session);

    let expectations = [
        (0, AnomalyType::Normal),
        (1, AnomalyType::SingleSensorFault),
        (2, AnomalyType::MultiSensorCorrelation),
        (3, AnomalyType::Unknown),
    ];
    for (channel, expected) in expectations {
        let result = classifier.classify(&window_favoring(channel)).unwrap();
        assert_eq!(
            result.anomaly_type, expected,
            "channel {channel} should map to {expected:?}"
        );
        assert!(
            result.confidence > 0.25 && result.confidence <= 1.0,
            "confidence in (0.25, 1.0], got {}",
            result.confidence
        );
    }
}

#[test]
fn uniform_window_yields_uniform_probabilities() {
    let session = load_verified_model(&fixture_path(), &fixture_hash()).unwrap();
    let mut classifier = Classifier::new(session);
    let window = [1.0f32; WINDOW_SIZE];
    let result = classifier.classify(&window).unwrap();
    // All channel means equal -> softmax uniform -> confidence ~0.25.
    assert!((result.confidence - 0.25).abs() < 1e-3);
}
